### ISSUE TITLE
Add exclusion rule to build-test.yml

### ISSUE THREAD

**Issue by yada** [microcks/microcks-testcontainers-java-spring-demo#24]
### Reason/Context

Related to .github replication workflow, see: https://github.com/microcks/.github/issues/16

### Description

Missing exclusion rule in build workflow

### Implementation ideas

From:
```
on:
  push:
    branches:
      - '**'
```

To:
```
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
```
